In [4]:
import pandas as pd
df = pd.read_excel(r"Bookings-100000-Rows (3).xlsx")

In [5]:
df.head()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,NaN
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,NaN
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,NaN
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,Driver is not moving towards pickup location,NaN,NaN,NaN,384,NaN,0,NaN,NaN,NaN
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,NaN

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 20 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  datetime64[us]
 1   Time                        103024 non-null  object
 2   Booking_ID                  103024 non-null  str
 3   Booking_Status              103024 non-null  str
 4   Customer_ID                 103024 non-null  str
 5   Vehicle_Type                103024 non-null  str
 6   Pickup_Location             103024 non-null  str
 7   Drop_Location               103024 non-null  str
 8   V_TAT                       63967 non-null   float64
 9   C_TAT                       63967 non-null   float64
 10  Canceled_Rides_by_Customer  10499 non-null   str
 11  Canceled_Rides_by_Driver    18434 non-null   str
 12  Incomplete_Rides            63967 non-null   str
 13  Incomplete_Rides_Reason     3926 non-null    str
 14  Booking_Value               103024 non-null  int64
 15  Payment_Method              63967 non-null   str
 16  Ride_Distance               103024 non-null  int64
 17  Driver_Ratings              63967 non-null   float64
 18  Customer_Rating             63967 non-null   float64
 19  Vehicle Images              0 non-null       float64
dtypes: datetime64[us](1), float64(5), int64(2), object(1), str(11)
memory usage: 15.7+ MB

Data Quality Check

In [8]:
# Shape
print(df.shape)

# Data Types
print(df.dtypes)

# Duplicate Rows
print("Duplicate Rows:", df.duplicated().sum())

# Duplicate Booking IDs
print("Duplicate Booking IDs:", df["Booking_ID"].duplicated().sum())

# Null Values
print(df.isnull().sum())

# Statistical Summary
print(df.describe(include="all"))

(103024, 20)
Date                          datetime64[us]
Time                                  object
Booking_ID                               str
Booking_Status                           str
Customer_ID                              str
Vehicle_Type                             str
Pickup_Location                          str
Drop_Location                            str
V_TAT                                float64
C_TAT                                float64
Canceled_Rides_by_Customer               str
Canceled_Rides_by_Driver                 str
Incomplete_Rides                         str
Incomplete_Rides_Reason                  str
Booking_Value                          int64
Payment_Method                           str
Ride_Distance                          int64
Driver_Ratings                       float64
Customer_Rating                      float64
Vehicle Images                       float64
dtype: object
Duplicate Rows: 0
Duplicate Booking IDs: 0
Date                               0
Time                               0
Booking_ID                         0
Booking_Status                     0
Customer_ID                        0
Vehicle_Type                       0
Pickup_Location                    0
Drop_Location                      0
V_TAT                          39057
C_TAT                          39057
Canceled_Rides_by_Customer     92525
Canceled_Rides_by_Driver       84590
Incomplete_Rides               39057
Incomplete_Rides_Reason        99098
Booking_Value                      0
Payment_Method                 39057
Ride_Distance                      0
Driver_Ratings                 39057
Customer_Rating                39057
Vehicle Images                103024
dtype: int64
                              Date      Time     Booking_ID Booking_Status  \
count                       103024    103024         103024         103024
unique                         NaN      1440         103024              4
top                            NaN  00:53:00  CNR7153255142        Success
freq                           NaN       101              1          63967
mean    2024-07-16 11:31:38.879678       NaN            NaN            NaN
min            2024-07-01 00:00:00       NaN            NaN            NaN
25%            2024-07-08 18:41:00       NaN            NaN            NaN
50%            2024-07-16 11:23:00       NaN            NaN            NaN
75%            2024-07-24 05:18:00       NaN            NaN            NaN
max            2024-07-31 23:58:00       NaN            NaN            NaN
std                            NaN       NaN            NaN            NaN

       Customer_ID Vehicle_Type Pickup_Location Drop_Location         V_TAT  \
count       103024       103024          103024        103024  63967.000000
unique       94544            7              50            50           NaN
top      CID954071  Prime Sedan    Banashankari        Peenya           NaN
freq             5        14877            2201          2159           NaN
mean           NaN          NaN             NaN           NaN    170.876952
min            NaN          NaN             NaN           NaN     35.000000
25%            NaN          NaN             NaN           NaN     98.000000
50%            NaN          NaN             NaN           NaN    168.000000
75%            NaN          NaN             NaN           NaN    238.000000
max            NaN          NaN             NaN           NaN    308.000000
std            NaN          NaN             NaN           NaN     80.803640

               C_TAT                    Canceled_Rides_by_Customer  \
count   63967.000000                                         10499
unique           NaN                                             5
top              NaN  Driver is not moving towards pickup location
freq             NaN                                          3175
mean       84.873372                                           NaN
min        25.000000                                           NaN
25%        55.000000                                           NaN
50%        85.000000                                           NaN
75%       115.000000                                           NaN
max       145.000000                                           NaN
std        36.005100                                           NaN

            Canceled_Rides_by_Driver Incomplete_Rides Incomplete_Rides_Reason  \
count                          18434            63967                    3926
unique                             4                2                       3
top     Personal & Car related issue               No         Customer Demand
freq                            6542            60041                    1601
mean                             NaN              NaN                     NaN
min                              NaN              NaN                     NaN
25%                              NaN              NaN                     NaN
50%                              NaN              NaN                     NaN
75%                              NaN              NaN                     NaN
max                              NaN              NaN                     NaN
std                              NaN              NaN                     NaN

        Booking_Value Payment_Method  Ride_Distance  Driver_Ratings  \
count   103024.000000          63967  103024.000000    63967.000000
unique            NaN              4            NaN             NaN
top               NaN           Cash            NaN             NaN
freq              NaN          35022            NaN             NaN
mean       548.751883            NaN      14.189927        3.997457
min        100.000000            NaN       0.000000        3.000000
25%        242.000000            NaN       0.000000        3.500000
50%        386.000000            NaN       8.000000        4.000000
75%        621.000000            NaN      26.000000        4.500000
max       2999.000000            NaN      49.000000        5.000000
std        536.541221            NaN      15.776270        0.576834

        Customer_Rating  Vehicle Images
count      63967.000000             0.0
unique              NaN             NaN
top                 NaN             NaN
freq                NaN             NaN
mean           3.998313             NaN
min            3.000000             NaN
25%            3.500000             NaN
50%            4.000000             NaN
75%            4.500000             NaN
max            5.000000             NaN
std            0.578957             NaN

                     Data cleaning part

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 19 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  datetime64[us]
 1   Time                        103024 non-null  object
 2   Booking_ID                  103024 non-null  str
 3   Booking_Status              103024 non-null  str
 4   Customer_ID                 103024 non-null  str
 5   Vehicle_Type                103024 non-null  str
 6   Pickup_Location             103024 non-null  str
 7   Drop_Location               103024 non-null  str
 8   V_TAT                       63967 non-null   float64
 9   C_TAT                       63967 non-null   float64
 10  Canceled_Rides_by_Customer  103024 non-null  str
 11  Canceled_Rides_by_Driver    103024 non-null  str
 12  Incomplete_Rides            63967 non-null   str
 13  Incomplete_Rides_Reason     103024 non-null  str
 14  Booking_Value               103024 non-null  int64
 15  Payment_Method              103024 non-null  str
 16  Ride_Distance               103024 non-null  int64
 17  Driver_Ratings              63967 non-null   float64
 18  Customer_Rating             63967 non-null   float64
dtypes: datetime64[us](1), float64(4), int64(2), object(1), str(11)
memory usage: 14.9+ MB

In [19]:
df.columns

Index(['Date', 'Time', 'Booking_ID', 'Booking_Status', 'Customer_ID',
       'Vehicle_Type', 'Pickup_Location', 'Drop_Location', 'V_TAT', 'C_TAT',
       'Canceled_Rides_by_Customer', 'Canceled_Rides_by_Driver',
       'Incomplete_Rides', 'Incomplete_Rides_Reason', 'Booking_Value',
       'Payment_Method', 'Ride_Distance', 'Driver_Ratings', 'Customer_Rating'],
      dtype='str')

In [ ]:
##vehicle image delete 
df.drop(columns=["Vehicle Images"], inplace=True)

In [20]:
# Customer cancellation reason
df["Canceled_Rides_by_Customer"] = df["Canceled_Rides_by_Customer"].fillna("Not Cancelled")

# Driver cancellation reason
df["Canceled_Rides_by_Driver"] = df["Canceled_Rides_by_Driver"].fillna("Not Cancelled")

# Incomplete ride reason
df["Incomplete_Rides_Reason"] = df["Incomplete_Rides_Reason"].fillna("Not Applicable")

# Payment method
df["Payment_Method"] = df["Payment_Method"].fillna("Not Applicable")

In [22]:
##veryfy null
df.isnull().sum()

Date                              0
Time                              0
Booking_ID                        0
Booking_Status                    0
Customer_ID                       0
Vehicle_Type                      0
Pickup_Location                   0
Drop_Location                     0
V_TAT                         39057
C_TAT                         39057
Canceled_Rides_by_Customer        0
Canceled_Rides_by_Driver          0
Incomplete_Rides              39057
Incomplete_Rides_Reason           0
Booking_Value                     0
Payment_Method                    0
Ride_Distance                     0
Driver_Ratings                39057
Customer_Rating               39057
dtype: int64

(Summary)

The missing values were analyzed based on business rules instead of blindly filling them. Cancellation reasons and payment details were populated with meaningful labels ("Not Cancelled", "Not Applicable") where appropriate. Operational metrics such as TAT and ratings were left as NULL because they are not generated for cancelled or incomplete rides. The Vehicle Images column was removed since it contained no data across all records.

Check Text Columns for Leading/Trailing Spaces

In [16]:
text_columns = [
    'Booking_ID',
    'Booking_Status',
    'Customer_ID',
    'Vehicle_Type',
    'Pickup_Location',
    'Drop_Location',
    'Canceled_Rides_by_Customer',
    'Canceled_Rides_by_Driver',
    'Incomplete_Rides',
    'Incomplete_Rides_Reason',
    'Payment_Method'
]

for col in text_columns:
    df[col] = df[col].str.strip()

In [17]:
##Verify
df[text_columns].head()

,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Payment_Method
0,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,Not Cancelled,Personal & Car related issue,NaN,Not Applicable,Not Applicable
1,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,Not Cancelled,Not Cancelled,No,Not Applicable,Cash
2,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,Not Cancelled,Not Cancelled,No,Not Applicable,UPI
3,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,Driver is not moving towards pickup location,Not Cancelled,NaN,Not Applicable,Not Applicable
4,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,Not Cancelled,Not Cancelled,No,Not Applicable,Credit Card

In [24]:
##Verify
print(df.columns)
print(df.shape)

Index(['Date', 'Time', 'Booking_ID', 'Booking_Status', 'Customer_ID',
       'Vehicle_Type', 'Pickup_Location', 'Drop_Location', 'V_TAT', 'C_TAT',
       'Canceled_Rides_by_Customer', 'Canceled_Rides_by_Driver',
       'Incomplete_Rides', 'Incomplete_Rides_Reason', 'Booking_Value',
       'Payment_Method', 'Ride_Distance', 'Driver_Ratings', 'Customer_Rating'],
      dtype='str')
(103024, 19)

In [18]:
##Check Unique Values
print(df["Booking_Status"].value_counts())

print(df["Vehicle_Type"].value_counts())

print(df["Payment_Method"].value_counts())

print(df["Incomplete_Rides"].value_counts(dropna=False))

Booking_Status
Success                 63967
Canceled by Driver      18434
Canceled by Customer    10499
Driver Not Found        10124
Name: count, dtype: int64
Vehicle_Type
Prime Sedan    14877
eBike          14816
Auto           14755
Prime Plus     14707
Bike           14662
Prime SUV      14655
Mini           14552
Name: count, dtype: int64
Payment_Method
Not Applicable    39057
Cash              35022
UPI               25881
Credit Card        2435
Debit Card          629
Name: count, dtype: int64
Incomplete_Rides
No     60041
NaN    39057
Yes     3926
Name: count, dtype: int64

In [26]:
##Time column check
df["Time"].head()

0    14:00:00
1    22:20:00
2    19:59:00
3    03:15:00
4    09:02:00
Name: Time, dtype: object

Time column was reviewed and found to be in a valid HH:MM:SS format. No transformation was required during the data cleaning process.

In [27]:
##check data type
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 19 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  datetime64[us]
 1   Time                        103024 non-null  object
 2   Booking_ID                  103024 non-null  str
 3   Booking_Status              103024 non-null  str
 4   Customer_ID                 103024 non-null  str
 5   Vehicle_Type                103024 non-null  str
 6   Pickup_Location             103024 non-null  str
 7   Drop_Location               103024 non-null  str
 8   V_TAT                       63967 non-null   float64
 9   C_TAT                       63967 non-null   float64
 10  Canceled_Rides_by_Customer  103024 non-null  str
 11  Canceled_Rides_by_Driver    103024 non-null  str
 12  Incomplete_Rides            63967 non-null   str
 13  Incomplete_Rides_Reason     103024 non-null  str
 14  Booking_Value               103024 non-null  int64
 15  Payment_Method              103024 non-null  str
 16  Ride_Distance               103024 non-null  int64
 17  Driver_Ratings              63967 non-null   float64
 18  Customer_Rating             63967 non-null   float64
dtypes: datetime64[us](1), float64(4), int64(2), object(1), str(11)
memory usage: 14.9+ MB

In [28]:
##Check Invalid Booking Value
print("Negative Booking Value :", (df["Booking_Value"] < 0).sum())

Negative Booking Value : 0

In [29]:
##Check Invalid Ride Distance
print("Negative Ride Distance :", (df["Ride_Distance"] < 0).sum())

Negative Ride Distance : 0

In [30]:
##Check Driver Rating
df[
    (df["Driver_Ratings"] < 1) |
    (df["Driver_Ratings"] > 5)
]

Empty DataFrame
Columns: [Date, Time, Booking_ID, Booking_Status, Customer_ID, Vehicle_Type, Pickup_Location, Drop_Location, V_TAT, C_TAT, Canceled_Rides_by_Customer, Canceled_Rides_by_Driver, Incomplete_Rides, Incomplete_Rides_Reason, Booking_Value, Payment_Method, Ride_Distance, Driver_Ratings, Customer_Rating]
Index: []

In [31]:
##Check Customer Rating
df[
    (df["Customer_Rating"] < 1) |
    (df["Customer_Rating"] > 5)
]

Empty DataFrame
Columns: [Date, Time, Booking_ID, Booking_Status, Customer_ID, Vehicle_Type, Pickup_Location, Drop_Location, V_TAT, C_TAT, Canceled_Rides_by_Customer, Canceled_Rides_by_Driver, Incomplete_Rides, Incomplete_Rides_Reason, Booking_Value, Payment_Method, Ride_Distance, Driver_Ratings, Customer_Rating]
Index: []

Feature Engineering

In [32]:
##Booking Month
df["booking_month"] = df["Date"].dt.month_name()

In [33]:
##Booking Day
df["booking_day"] = df["Date"].dt.day_name()

In [35]:
##Booking Hour
df["booking_hour"] = pd.to_datetime(
    df["Time"],
    format="%H:%M:%S",
    errors="coerce"
).dt.hour

In [38]:
df.head()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,...,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,booking_month,booking_day,booking_hour
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,...,NaN,Not Applicable,444,Not Applicable,0,NaN,NaN,July,Friday,14
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,...,No,Not Applicable,158,Cash,13,4.1,4.0,July,Thursday,22
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,...,No,Not Applicable,386,UPI,40,4.2,4.8,July,Tuesday,19
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,...,NaN,Not Applicable,384,Not Applicable,0,NaN,NaN,July,Monday,3
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,...,No,Not Applicable,822,Credit Card,45,4.0,3.0,July,Tuesday,9

Create Time Slot

In [39]:
def get_time_slot(hour):
    if 5 <= hour < 12:
        return "Morning"
    elif 12 <= hour < 17:
        return "Afternoon"
    elif 17 <= hour < 21:
        return "Evening"
    else:
        return "Night"

df["time_slot"] = df["booking_hour"].apply(get_time_slot)

In [40]:
##Verify
df[["Time", "booking_hour", "time_slot"]].head(10)

       Time  booking_hour  time_slot
0  14:00:00            14  Afternoon
1  22:20:00            22      Night
2  19:59:00            19    Evening
3  03:15:00             3      Night
4  09:02:00             9    Morning
5  04:42:00             4      Night
6  09:51:00             9    Morning
7  11:12:00            11    Morning
8  19:19:00            19    Evening
9  01:31:00             1      Night

Sql Server connection

In [41]:
%pip install sqlalchemy pyodbc

Requirement already satisfied: sqlalchemy in C:\Users\SASWAT\.conda\envs\notebook-env\Lib\site-packages (2.0.51)
Requirement already satisfied: pyodbc in C:\Users\SASWAT\.conda\envs\notebook-env\Lib\site-packages (5.3.0)
Requirement already satisfied: greenlet>=1 in C:\Users\SASWAT\.conda\envs\notebook-env\Lib\site-packages (from sqlalchemy) (3.5.3)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\SASWAT\.conda\envs\notebook-env\Lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [44]:
##Import Libraries
import pandas as pd
import pyodbc

from sqlalchemy import create_engine
from urllib.parse import quote_plus

In [45]:
###SQL Server Details
SERVER = r"LAPTOP-71G1NMQR\SQLEXPRESS"
DATABASE = "Ride_Booking_ETL"

In [46]:
##Create Connection String
connection_string = (
    "DRIVER={ODBC Driver 18 for SQL Server};"
    f"SERVER={SERVER};"
    f"DATABASE={DATABASE};"
    "Trusted_Connection=yes;"
)

In [47]:
##Create SQLAlchemy Engine
engine = create_engine(
    f"mssql+pyodbc:///?odbc_connect={quote_plus(connection_string)}"
)

print("Engine Created Successfully")

Engine Created Successfully

In [51]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

SERVER = r"LAPTOP-71G1NMQR\SQLEXPRESS"
DATABASE = "Ride_Booking_ETL"

connection_string = (
    "DRIVER={ODBC Driver 18 for SQL Server};"
    f"SERVER={SERVER};"
    f"DATABASE={DATABASE};"
    "Trusted_Connection=yes;"
    "TrustServerCertificate=yes;"
)

engine = create_engine(
    f"mssql+pyodbc:///?odbc_connect={quote_plus(connection_string)}"
)

print("Engine Created Successfully")

Engine Created Successfully

In [52]:
##Test Connection
with engine.connect() as conn:
    print("Connected Successfully")

Connected Successfully

In [56]:
##Load data 
df.to_sql(
    "stg_bookings",
    con=engine,
    if_exists="replace",
    index=False,
    chunksize=1000
)

9294

Future Automation

In [58]:
with engine.begin() as conn:
    conn.exec_driver_sql("EXEC usp_Load_Bookings")